backend:
  name: github

  repo: github.com/clarakk/Somma-spese-copia
  branch: master
  site_domain: tabellagit.netlify.app
  
media_folder: "static/images"
public_folder: "/images"

collections:
<<<<<<< HEAD
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
=======
  - name: "expenses"
    label: "Expenses"
    folder: "content/expenses"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "date" }
      - { name: "text", label: "Text", widget: "string" }
      - { name: "number", label: "Number", widget: "number" }
>>>>>>> 48ebb5fd10d5cc4e497490892daad91ec8cac79f
