backend:
name: git-gateway
  branch: main
  repo: github.com/clarakk/Somma-spese-copia
  
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "expenses"
    label: "Expenses"
    folder: "content/expenses"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "date" }
      - { name: "text", label: "Text", widget: "string" }
      - { name: "number", label: "Number", widget: "number" }
